services:
  accounts:
    image: "nagarjun20/accounts:s1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nagarjun20
  loans:
    image: "nagarjun20/loans:s1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nagarjun20
  cards:
    image: "nagarjun20/cards:s1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nagarjun20
networks:
  nagarjun20:
    driver: "bridge"